author: David Susco
description: The home of high-quality, 10mm fantasy and historical minis.
keywords:
  - warmonger
  - miniatures
  - 10mm
  - minis
  - warmaster
  - ancients
  - fantasy
  - game
  - historical
  - medieval
  - renaissance
  - wargame
scripts:
  - //code.jquery.com/jquery-2.1.4.min.js
  - //maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js
  - //cdnjs.cloudflare.com/ajax/libs/blueimp-gallery/2.16.0/js/jquery.blueimp-gallery.min.js
  - //cdn.jsdelivr.net/bootstrap.image-gallery/3.1.0/js/bootstrap-image-gallery.min.js
  - /assets/js/warmonger-miniatures.js
stylesheets:
  - /assets/css/warmonger-miniatures.css
tagline: 10mm for the Aspiring Warmaster
title: Warmonger Miniatures

# Where things are
source: ./_site
destination: ./public_html

# Outputting
timezone: America/New_York

defaults:
  -
    values:
      layout: default