author: David Susco
description: The home of high-quality, 10mm fantasy and historical minis.
keywords:
  - warmonger
  - miniatures
  - 10mm
  - minis
  - warmaster
  - ancients
  - fantasy
  - game
  - historical
  - medieval
  - renaissance
  - wargame
scripts:
  - /assets/js/warmonger-miniatures.js
stylesheets:
  - /assets/css/warmonger-miniatures.css
tagline: 10mm for the Aspiring Warmaster
title: Warmonger Miniatures

# LESS
less:
  paths:
    - ./bower_components
    - ./_site/_assets/stylesheets

# CSS
css:
  compress: true

# Tags
tag_index_permalink: /news/tag/:tag
tag_index_title: :tag News

# Where things are
source: ./_site
destination: ./public_html

# Outputting
permalink: /news/:year/:month/:title.html
timezone: America/New_York

defaults:
  -
    values:
      layout: default
  -
    scope:
      type: pages
    values:
      layout: page
      permalink: /:path/:basename:output_ext
  -
    scope:
      type: posts
    values:
      author: Dave
      layout: post
  -
    scope:
      path: news
    values:
      local_nav: /news/
  -
    scope:
      path: store
    values:
      layout: product
      local_nav: /store/
  -
    scope:
      path: tags
    values:
      local_nav: /news/
