author: David Susco
description: The home of high-quality, 10mm fantasy and historical minis.
scripts:
  - https://cdnjs.cloudflare.com/ajax/libs/lodash.js/4.17.11/lodash.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js
stylesheets:
  - https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.7.0/animate.min.css
  - https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css
tagline: 10mm for the Aspiring Warmaster
title: Warmonger Miniatures

# Where things are
source: ./_site
destination: ./public_html
collections:
  posts:
    permalink: news/:year/:month/:title:output_ext
  products:
    output: true
    permalink: store/:path:output_ext

# Plugins
plugins:
  - jekyll-assets

# Outputting
timezone: America/New_York

# defaults
defaults:
  -
    values:
      layout: page
  -
    scope:
      type: posts
    values:
      author: Dave
      layout: post
  -
    scope:
      type: products
    values:
      layout: product
  -
    scope:
      path: news
      type: pages
    values:
      breadcrumb_template: '%{date}'
      heading_template: 'Warmonger Miniatures %{full_date} News'
      paginate: 5
      title_template: '%{full_date} News'
  -
    scope:
      path: news/tags
      type: pages
    values:
      breadcrumb_template: '%{tag}'
      heading_template: 'Warmonger Miniatures %{tag} News'
      title_template: '%{tag} News'
  -
    scope:
      path: store/index.html
    values:
      heading: Warmonger Miniatures Store
  -
    scope:
      path: store/10mm-landsknechte/index.html
    values:
      image: http://res.cloudinary.com/warmonger-miniatures/image/upload/v1543432101/warmonger-miniatures.com/ls01/ls01.jpg
